FROM eclipse-temurin:21-jre-alpine
WORKDIR /deployments
  
  # Pull pre-compiled folders directly out of the GitHub runner's target directory
COPY target/quarkus-app/lib/ /deployments/lib/
COPY target/quarkus-app/*.jar /deployments/
COPY target/quarkus-app/app/ /deployments/app/
COPY target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/deployments/quarkus-run.jar"]